config/routes.rb
Kegup::Application.routes.draw do
  resources :distributors

  ActiveAdmin.routes(self)
  # Authentication
  get 'auth/facebook'
  get 'auth/logout' => 'auth#logout'
  get 'auth/facebook/callback' => 'auth#facebook'

  resources :orgs do
    resources :org_user_memberships
    resources :kegs
  end

  resources :users, only: [:show, :edit, :update]
  resources :users_favorite_beers, path: 'my-beers'


  namespace :api do
    resources :orgs do
      member do
        get 'bother'
      end

      resources :taps do
        member do
          patch 'finished'
          patch 'tapped'
        end
      end
    end
  end

  root 'website#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associations =======================================================================================================
  has_many :org_user_memberships
  has_many :orgs, through: :org_user_memberships

  has_many :favorite_beers, class_name: Users::FavoriteBeer
  has_many :beers, through: :favorite_beers

  # Validations ========================================================================================================
  validates :email, uniqueness: true, format: /\A.+@.+\..+\z/i, allow_blank: true

  # Class Methods ======================================================================================================
  def self.from_facebook auth_hash
    find_or_create_by!(fb_id: auth_hash[:uid]) do |user|
      user.first_name        = auth_hash[:info][:first_name]
      user.last_name         = auth_hash[:info][:last_name]
      user.email             = auth_hash[:info][:email]
      user.fb_token          = auth_hash[:credentials][:token]
      user.fb_token_expires  = auth_hash[:credentials][:expires_at]
      user.avatar_url        = auth_hash[:info][:image]
      user.fb_profile_url    = auth_hash[:info][:urls][:Facebook]
    end
  end


  # Callbacks ==========================================================================================================


  # Instance Methods ===================================================================================================
  def name
    "#{first_name} #{last_name}"
  end

  def kegmeister_for org
    kegmeister_orgs.include? org
  end

  def member_for org
    orgs.include? org
  end

  def kegmeister_orgs
    @kegmeister_orgs ||= self.orgs.merge(OrgUserMembership.kegmeisters)
  end

  def beers_with_favorite_id
    beers.select('beers.*, users_favorite_beers.id as favorite_beer_id')
  end

  def high_res_avatar_url(width=20,height=20)
    "http://graph.facebook.com/#{self.fb_id}/picture?width=#{width}&height=#{height}"
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/models/users/favorite_beer.rb
class Users::FavoriteBeer < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer

  validates :beer_id, uniqueness: { scope: :user_id, message: "has already been added" }

  validate :user_count, on: :create

   def user_count
     errors.add(:too_many, "favorite beers for #{self.user.name} (Max 3)") if self.class.where(user_id: self.user_id).count >= 3
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])

    authorize! :update, @user
  end

  def update
    @user = User.find(params[:id])

    authorize! :update, @user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.haml
.container
  .row
    .col-lg-3
      %h1
        = link_to image_tag(@user.high_res_avatar_url(230, 230), size: '230x230'), @user.fb_profile_url

    .col-lg-6
      %h1
        = @user.name

      %hr

      %p
        %h4 Organizations

        %ul.org-list
          - @user.orgs.each do |org|
            %li
              = link_to org.name, org_path(org)
              - if current_user.kegmeister_for(@org)
                /  ToDo, find this glphyicon
                %span.glyphicon.glyphicon-crown

  .row
    .col-lg-9
      = cache [@user, 'beers'] do
        .row{style: 'margin-top: 1.75em'}
          .col-lg-12
            = render 'shared/beer_list', beers: @user.beers, title: 'Favorite Beers', edit_btn: true

app/views/users/show.haml
.container
  .row
    .col-lg-3
      %h1
        =link_to image_tag(@user.high_res_avatar_url(230, 230), size: '230x230'), @user.fb_profile_url

    .col-lg-6
      %h1
        = @user.name

      %p
        Joined on
        = @user.created_at.strftime('%B %d, %Y')
        %br
        Last login on
        = @user.updated_at.strftime('%B %d, %Y')

      %hr

      %p
        %h4 Organizations

        %ul.org-list
        - @user.orgs.each do |org|
          %li
            = link_to org.name, org_path(org)

  .row
    .col-lg-9
      = cache [@user, 'beers'] do
        .row{style: 'margin-top: 1.75em'}
          .col-lg-12
            = render 'shared/beer_list', beers: @user.beers, title: 'Favorite Beers'