config/routes.rb
Kegup::Application.routes.draw do
  resources :distributors

  ActiveAdmin.routes(self)
  # Authentication
  get 'auth/facebook'
  get 'auth/logout' => 'auth#logout'
  get 'auth/facebook/callback' => 'auth#facebook'

  resources :orgs do
    resources :org_user_memberships
    resources :kegs
  end

  resources :users, only: [:show, :edit, :update]
  resources :users_favorite_beers, path: 'my-beers'


  namespace :api do
    resources :orgs do
      member do
        get 'bother'
      end

      resources :taps do
        member do
          patch 'finished'
          patch 'tapped'
        end
      end
    end
  end

  root 'website#index'
end

app/views/shared/_beer_list.haml
- edit_btn ||= false

%h3
  = title
  - if edit_btn
    = link_to 'Edit', users_favorite_beers_path, class: "btn btn-success btn-sm"
%hr
- if beers.present?
  %table.table.table-hover.table-stripped.beer-table
    %thead
      %tr
        %th

        %th
          Beer
        %th
          Origin
        %th
          Style
        %th
          ABV
        - if block_given?
          %th
            / Actions



    %tbody
      - beers.each do |beer|
        %tr
          %td.text-center.mid
            = image_tag(beer.image_url(:small).to_s)
          %td.mid
            = beer.name
          %td.mid
            = beer.origin
          %td.mid
            = beer.style
          %td.mid
            = "#{beer.abv}%"
          - if block_given?
            %td.mid
              = yield beer

- else
  No beer available...