config/routes.rb
Kegup::Application.routes.draw do
  resources :distributors

  ActiveAdmin.routes(self)
  # Authentication
  get 'auth/facebook'
  get 'auth/logout' => 'auth#logout'
  get 'auth/facebook/callback' => 'auth#facebook'

  resources :orgs do
    resources :org_user_memberships
    resources :kegs
  end

  resources :users, only: [:show, :edit, :update]
  resources :users_favorite_beers, path: 'my-beers'


  namespace :api do
    resources :orgs do
      member do
        get 'bother'
      end

      resources :taps do
        member do
          patch 'finished'
          patch 'tapped'
        end
      end
    end
  end

  root 'website#index'
end

app/controllers/users_favorite_beers_controller.rb
class UsersFavoriteBeersController < ApplicationController
  def index
    if current_user.present?
      @favorite_beers = current_user.beers_with_favorite_id.load
    else
      redirect_to root_path
    end
  end

  def create
    beer = Beer.find(params[:users_favorite_beer][:beer_id])
    current_user.favorite_beers.create!(beer: beer)
    flash[:success] = "Added #{beer.name} to your favorite beers."
  rescue ActiveRecord::RecordInvalid => e
    flash[:danger] = e.message
  rescue => e
    log_error e
    flash[:danger] = "Unable to add beer to your favorite beers."
  ensure
    redirect_to :back
  end

  def destroy
    fav_beer = current_user.favorite_beers.find(params[:id])
    fav_beer.destroy!
    flash[:success] = "Removed #{fav_beer.beer.name} from your favorite beers."
  rescue => e
    log_error e
    flash[:danger] = "Unable to remove that beer from your favorite beers."
  ensure
    redirect_to :back
  end
end

app/views/users_favorite_beers/index.haml
.container
  .row
    .col-lg-12
      %h1
        My Beers

  .row
    .col-lg-12
      = render layout: 'shared/beer_list', locals: { beers: @favorite_beers, title: nil } do |beer|
        = link_to 'Remove', users_favorite_beer_path(beer.favorite_beer_id), method: :delete, class: 'btn btn-sm btn-danger membership-delete'

  .row
    .col-lg-12
      %h3
        Add Beer to Favorites
      %hr
      .row
        - if @favorite_beers.size < 3
          .col-lg-4.col-lg-offset-4.well.text-center
            = form_for Users::FavoriteBeer.new, html: { role: 'form' }  do |f|
              %div.form-group
                = f.label :beer_id, "Choose a favorite beer"
                = f.collection_select :beer_id, Beer.all, :id, :brewery_and_name

              %div.form-group
                = f.submit "Add Beer to Favorites!", class: "btn btn-primary btn-block btn-success"
        - else
          .col-lg-12.well.text-center
            You have reached the maximum number of favorite beers. Please remove one to add another